name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  flutter_svg: ^1.0.0
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  provider: ^6.0.5
  upi_pay: ^1.1.0
  android_intent_plus: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - .env